# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NesosTechnology
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 NesosTechnology - I do infosec for fun and no profit - DIY Security researcher
baseurl: ""
url: ""
post_limit: 5
# Footer
footer_left: > 
 NesosTechnology<br>
 I do infosec for fun and no profit<br>
 DIY Security Researcher
footer_right: "Contacts? If you know me, you know how to contact me.<br>If you don't, feel free to open a GitHub issue for any request"

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# Handling Reading
safe:         true
include:      [".htaccess"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/

# Build settings
defaults: [{values: {layout: "post"}}]